name: Windows Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      CI: true
      CONFIRM_DROP: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Start PostgreSQL
        run: |
          $postgreSqlSvc = Get-Service "postgresql*"
          Set-Service $postgreSqlSvc.Name -StartupType manual
          $postgreSqlSvc.Start()
          $env:PATH += ";$env:PGBIN"
          $env:PGPASSWORD = "root"
          $postgreSqlSvc.WaitForStatus('Running')
          psql -U postgres -d postgres -c "alter user postgres with password 'postgres'";
          Restart-Service $postgreSqlSvc
      - name: yarn, lint, build and test
        run: |
          $env:PATH += ";$env:PGBIN"
          cp .env.ci .env
          yarn --frozen-lockfile
          yarn setup
          yarn build
          yarn lint
          yarn test --ci
          yarn depcheck
